### ISSUE TITLE
Other map box styles

### ISSUE THREAD

**Issue by dominijk** [tomchadwin/mapbox-gl-js#1]
Do you have the json for the light and dark zoomstack styles? I think I've seen it some place but can't now find it and want to explore it

**Comment by tomchadwin** [comment]
Here?

https://github.com/OrdnanceSurvey/OS-Open-Zoomstack-Stylesheets/tree/master/Vector%20Tiles/Mapbox%20GL%20Styles

**Comment by dominijk** [comment]
Thank you Tom!
